# PURPOSE: Handle Google OAuth and Email auth via Supabase
# The frontend will call these endpoints for login/signup

from fastapi import APIRouter, HTTPException
from fastapi.responses import RedirectResponse, JSONResponse
from supabase import create_client
from config import SUPABASE_URL, SUPABASE_SERVICE_KEY, FRONTEND_URL
from pydantic import BaseModel
from typing import Optional

router = APIRouter()
supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)

class EmailAuthRequest(BaseModel):
    email: str
    password: str
    name: Optional[str] = None  # Only for signup

# ── GOOGLE OAUTH ──────────────────────────────────────────
@router.get("/google")
def google_login():
    """
    1. Call supabase.auth.sign_in_with_oauth(provider="google", options={redirect_to: FRONTEND_URL/auth-callback.html})
    2. Get the URL from the response
    3. Return RedirectResponse to that URL
    """
    try:
        # Use python-supabase oauth sign-in.
        # Pass dictionary credentials structure
        res = supabase.auth.sign_in_with_oauth({
            "provider": "google",
            "options": {
                "redirect_to": f"{FRONTEND_URL}/auth-callback.html"
            }
        })
        url = getattr(res, "url", None)
        if not url:
            raise HTTPException(status_code=500, detail="OAuth URL not generated by Supabase.")
        return RedirectResponse(url)
    except Exception as e:
        print(f"Google OAuth sign-in error: {e}")
        raise HTTPException(status_code=500, detail=f"OAuth error: {str(e)}")

# ── EMAIL SIGNUP ──────────────────────────────────────────
@router.post("/signup")
def signup(req: EmailAuthRequest):
    """
    1. Call supabase.auth.sign_up({"email": req.email, "password": req.password})
    2. If error → raise HTTPException 400 with error message
    3. If success:
       a. Insert into public.profiles table: {id: user.id, name: req.name, email: req.email}
       b. Return: {"success": true, "message": "Check your email to confirm signup"}
    """
    try:
        # Call supabase auth sign_up
        res = supabase.auth.sign_up({
            "email": req.email,
            "password": req.password
        })
        user = res.user
        if not user:
            raise HTTPException(status_code=400, detail="Signup failed.")
            
        # Try inserting profile (in case database trigger fails or needs override)
        # Note: profiles table does not contain email column, so we exclude it to prevent SQL error.
        try:
            profile_data = {
                "id": user.id,
                "name": req.name if req.name else user.email
            }
            supabase.table("profiles").upsert(profile_data).execute()
        except Exception as db_err:
            print(f"Database profiles insert ignored or handled by trigger: {db_err}")
            
        return {"success": True, "message": "Check your email to confirm signup"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

# ── EMAIL LOGIN ───────────────────────────────────────────
@router.post("/login")
def login(req: EmailAuthRequest):
    """
    1. Call supabase.auth.sign_in_with_password({"email": req.email, "password": req.password})
    2. If error → raise HTTPException 401: "Invalid email or password"
    3. If success → return:
    {
        "success": true,
        "access_token": session.access_token,
        "user": {
            "id": user.id,
            "email": user.email,
            "name": profile.name
        }
    }
    """
    try:
        res = supabase.auth.sign_in_with_password({
            "email": req.email,
            "password": req.password
        })
        session = res.session
        user = res.user
        if not session or not user:
            raise HTTPException(status_code=401, detail="Invalid email or password")
            
        # Retrieve user profile
        name = user.email
        try:
            profile_res = supabase.table("profiles").select("name").eq("id", user.id).single().execute()
            if profile_res.data:
                name = profile_res.data.get("name", user.email)
        except Exception as db_err:
            print(f"Failed to fetch user name from database: {db_err}")
            
        return {
            "success": True,
            "access_token": session.access_token,
            "user": {
                "id": user.id,
                "email": user.email,
                "name": name
            }
        }
    except Exception as e:
        print(f"Login failed: {e}")
        raise HTTPException(status_code=401, detail="Invalid email or password")

# ── GET USER PROFILE ──────────────────────────────────────
@router.get("/profile")
def get_profile(user_id: str):
    """
    1. Query: supabase.table("profiles").select("*").eq("id", user_id).single()
    2. Return the profile data
    """
    try:
        res = supabase.table("profiles").select("*").eq("id", user_id).single().execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Profile not found")
        return res.data
    except Exception as e:
        print(f"Get profile failed: {e}")
        raise HTTPException(status_code=404, detail=f"Profile not found: {str(e)}")

# ── UPDATE USER PROFILE ───────────────────────────────────
@router.put("/profile")
def update_profile(user_id: str, name: str, phone: str = None, address: str = None):
    """
    1. Update supabase.table("profiles") where id = user_id
    2. Return updated profile
    """
    try:
        update_data = {"name": name}
        if phone is not None:
            update_data["phone"] = phone
        if address is not None:
            update_data["address"] = address
            
        res = supabase.table("profiles").update(update_data).eq("id", user_id).execute()
        if not res.data:
            raise HTTPException(status_code=404, detail="Profile not found for update")
        return res.data[0]
    except Exception as e:
        print(f"Update profile failed: {e}")
        raise HTTPException(status_code=400, detail=str(e))

# ── LOGOUT ────────────────────────────────────────────────
@router.post("/logout")
def logout(access_token: str):
    """
    1. Call supabase.auth.sign_out() with the token
    2. Return: {"success": true}
    """
    try:
        # Call sign_out in Supabase
        supabase.auth.sign_out()
        return {"success": True}
    except Exception as e:
        print(f"Logout failed: {e}")
        return {"success": True}
